/*
 A JavaScript implementation of the SHA family of hashes, as
 defined in FIPS PUB 180-4 and FIPS PUB 202, as well as the corresponding
 HMAC implementation as defined in FIPS PUB 198a

 Copyright Brian Turek 2008-2016
 Distributed under the BSD License
 See http://caligatio.github.com/jsSHA/ for more information

 Several functions taken from Paul Johnston
*/
(function(G){function r(d,b,c){var g=0,a=[],e=0,h,p,q,f,k,m,n,t,w=!1,l=[],u=[],v,r=!1;c=c||{};h=c.encoding||"UTF8";v=c.numRounds||1;if(v!==parseInt(v,10)||1>v)throw Error("numRounds must a integer >= 1");if("SHA-1"===d)k=512,m=z,n=H,f=160,t=function(a){return a.slice()};else throw Error("Chosen SHA variant is not supported");q=A(b,h);p=x(d);this.setHMACKey=function(a,e,b){var c;if(!0===w)throw Error("HMAC key already set");if(!0===r)throw Error("Cannot set HMAC key after calling update");h=(b||{}).encoding||
"UTF8";e=A(e,h)(a);a=e.binLen;e=e.value;c=k>>>3;b=c/4-1;if(c<a/8){for(e=n(e,a,0,x(d),f);e.length<=b;)e.push(0);e[b]&=4294967040}else if(c>a/8){for(;e.length<=b;)e.push(0);e[b]&=4294967040}for(a=0;a<=b;a+=1)l[a]=e[a]^909522486,u[a]=e[a]^1549556828;p=m(l,p);g=k;w=!0};this.update=function(b){var f,h,d,c=0,n=k>>>5;f=q(b,a,e);b=f.binLen;h=f.value;f=b>>>5;for(d=0;d<f;d+=n)c+k<=b&&(p=m(h.slice(d,d+n),p),c+=k);g+=c;a=h.slice(c>>>5);e=b%k;r=!0};this.getHash=function(b,h){var c,q,k,m;if(!0===w)throw Error("Cannot call getHash after setting HMAC key");
k=B(h);switch(b){case "HEX":c=function(a){return C(a,f,k)};break;case "B64":c=function(a){return D(a,f,k)};break;case "BYTES":c=function(a){return E(a,f)};break;case "ARRAYBUFFER":try{q=new ArrayBuffer(0)}catch(I){throw Error("ARRAYBUFFER not supported by this environment");}c=function(a){return F(a,f)};break;default:throw Error("format must be HEX, B64, BYTES, or ARRAYBUFFER");}m=n(a.slice(),e,g,t(p),f);for(q=1;q<v;q+=1)m=n(m,f,0,x(d),f);return c(m)};this.getHMAC=function(b,h){var c,q,l,r;if(!1===
w)throw Error("Cannot call getHMAC without first setting HMAC key");l=B(h);switch(b){case "HEX":c=function(a){return C(a,f,l)};break;case "B64":c=function(a){return D(a,f,l)};break;case "BYTES":c=function(a){return E(a,f)};break;case "ARRAYBUFFER":try{c=new ArrayBuffer(0)}catch(I){throw Error("ARRAYBUFFER not supported by this environment");}c=function(a){return F(a,f)};break;default:throw Error("outputFormat must be HEX, B64, BYTES, or ARRAYBUFFER");}q=n(a.slice(),e,g,t(p),f);r=m(u,x(d));r=n(q,f,
k,r,f);return c(r)}}function C(d,b,c){var g="";b/=8;var a,e;for(a=0;a<b;a+=1)e=d[a>>>2]>>>8*(3+a%4*-1),g+="0123456789abcdef".charAt(e>>>4&15)+"0123456789abcdef".charAt(e&15);return c.outputUpper?g.toUpperCase():g}function D(d,b,c){var g="",a=b/8,e,h,p;for(e=0;e<a;e+=3)for(h=e+1<a?d[e+1>>>2]:0,p=e+2<a?d[e+2>>>2]:0,p=(d[e>>>2]>>>8*(3+e%4*-1)&255)<<16|(h>>>8*(3+(e+1)%4*-1)&255)<<8|p>>>8*(3+(e+2)%4*-1)&255,h=0;4>h;h+=1)8*e+6*h<=b?g+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(p>>>
6*(3-h)&63):g+=c.b64Pad;return g}function E(d,b){var c="",g=b/8,a,e;for(a=0;a<g;a+=1)e=d[a>>>2]>>>8*(3+a%4*-1)&255,c+=String.fromCharCode(e);return c}function F(d,b){var c=b/8,g,a=new ArrayBuffer(c);for(g=0;g<c;g+=1)a[g]=d[g>>>2]>>>8*(3+g%4*-1)&255;return a}function B(d){var b={outputUpper:!1,b64Pad:"=",shakeLen:-1};d=d||{};b.outputUpper=d.outputUpper||!1;!0===d.hasOwnProperty("b64Pad")&&(b.b64Pad=d.b64Pad);d.hasOwnProperty("shakeLen");if("boolean"!==typeof b.outputUpper)throw Error("Invalid outputUpper formatting option");
if("string"!==typeof b.b64Pad)throw Error("Invalid b64Pad formatting option");return b}function A(d,b){var c;switch(b){case "UTF8":case "UTF16BE":case "UTF16LE":break;default:throw Error("encoding must be UTF8, UTF16BE, or UTF16LE");}switch(d){case "HEX":c=function(b,a,e){var h=b.length,c,g,f,d,m;if(h%2)throw Error("String of HEX type must be in byte increments");a=a||[0];e=e||0;m=e>>>3;for(c=0;c<h;c+=2){g=parseInt(b.substr(c,2),16);if(isNaN(g))throw Error("String of HEX type contains invalid characters");
d=(c>>>1)+m;for(f=d>>>2;a.length<=f;)a.push(0);a[f]|=g<<8*(3+d%4*-1)}return{value:a,binLen:4*h+e}};break;case "TEXT":c=function(c,a,e){var h,d,g=0,f,k,m,n,t,l;a=a||[0];e=e||0;m=e>>>3;if("UTF8"===b)for(l=3,f=0;f<c.length;f+=1)for(h=c.charCodeAt(f),d=[],128>h?d.push(h):2048>h?(d.push(192|h>>>6),d.push(128|h&63)):55296>h||57344<=h?d.push(224|h>>>12,128|h>>>6&63,128|h&63):(f+=1,h=65536+((h&1023)<<10|c.charCodeAt(f)&1023),d.push(240|h>>>18,128|h>>>12&63,128|h>>>6&63,128|h&63)),k=0;k<d.length;k+=1){t=g+
m;for(n=t>>>2;a.length<=n;)a.push(0);a[n]|=d[k]<<8*(l+t%4*-1);g+=1}else if("UTF16BE"===b||"UTF16LE"===b)for(l=2,f=0;f<c.length;f+=1){h=c.charCodeAt(f);"UTF16LE"===b&&(k=h&255,h=k<<8|h>>>8);t=g+m;for(n=t>>>2;a.length<=n;)a.push(0);a[n]|=h<<8*(l+t%4*-1);g+=2}return{value:a,binLen:8*g+e}};break;case "B64":c=function(b,a,e){var c=0,d,g,f,k,m,n,l;if(-1===b.search(/^[a-zA-Z0-9=+\/]+$/))throw Error("Invalid character in base-64 string");g=b.indexOf("=");b=b.replace(/\=/g,"");if(-1!==g&&g<b.length)throw Error("Invalid '=' found in base-64 string");
a=a||[0];e=e||0;n=e>>>3;for(g=0;g<b.length;g+=4){m=b.substr(g,4);for(f=k=0;f<m.length;f+=1)d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".indexOf(m[f]),k|=d<<18-6*f;for(f=0;f<m.length-1;f+=1){l=c+n;for(d=l>>>2;a.length<=d;)a.push(0);a[d]|=(k>>>16-8*f&255)<<8*(3+l%4*-1);c+=1}}return{value:a,binLen:8*c+e}};break;case "BYTES":c=function(b,a,e){var c,d,g,f,k;a=a||[0];e=e||0;g=e>>>3;for(d=0;d<b.length;d+=1)c=b.charCodeAt(d),k=d+g,f=k>>>2,a.length<=f&&a.push(0),a[f]|=c<<8*(3+k%4*-1);
return{value:a,binLen:8*b.length+e}};break;case "ARRAYBUFFER":try{c=new ArrayBuffer(0)}catch(g){throw Error("ARRAYBUFFER not supported by this environment");}c=function(b,a,c){var d,e,g,f;a=a||[0];c=c||0;e=c>>>3;for(d=0;d<b.byteLength;d+=1)f=d+e,g=f>>>2,a.length<=g&&a.push(0),a[g]|=b[d]<<8*(3+f%4*-1);return{value:a,binLen:8*b.byteLength+c}};break;default:throw Error("format must be HEX, TEXT, B64, BYTES, or ARRAYBUFFER");}return c}function l(d,b){return d<<b|d>>>32-b}function u(d,b){var c=(d&65535)+
(b&65535);return((d>>>16)+(b>>>16)+(c>>>16)&65535)<<16|c&65535}function y(d,b,c,g,a){var e=(d&65535)+(b&65535)+(c&65535)+(g&65535)+(a&65535);return((d>>>16)+(b>>>16)+(c>>>16)+(g>>>16)+(a>>>16)+(e>>>16)&65535)<<16|e&65535}function x(d){if("SHA-1"===d)d=[1732584193,4023233417,2562383102,271733878,3285377520];else throw Error("No SHA variants supported");return d}function z(d,b){var c=[],g,a,e,h,p,q,f;g=b[0];a=b[1];e=b[2];h=b[3];p=b[4];for(f=0;80>f;f+=1)c[f]=16>f?d[f]:l(c[f-3]^c[f-8]^c[f-14]^c[f-16],
1),q=20>f?y(l(g,5),a&e^~a&h,p,1518500249,c[f]):40>f?y(l(g,5),a^e^h,p,1859775393,c[f]):60>f?y(l(g,5),a&e^a&h^e&h,p,2400959708,c[f]):y(l(g,5),a^e^h,p,3395469782,c[f]),p=h,h=e,e=l(a,30),a=g,g=q;b[0]=u(g,b[0]);b[1]=u(a,b[1]);b[2]=u(e,b[2]);b[3]=u(h,b[3]);b[4]=u(p,b[4]);return b}function H(d,b,c,g){var a;for(a=(b+65>>>9<<4)+15;d.length<=a;)d.push(0);d[b>>>5]|=128<<24-b%32;b+=c;d[a]=b&4294967295;d[a-1]=b/4294967296|0;b=d.length;for(a=0;a<b;a+=16)g=z(d.slice(a,a+16),g);return g}G.jsSHA=r;"function"===typeof define&&
define.amd?define("jsSHA",[],function(){return r}):"undefined"!==typeof exports&&("undefined"!==typeof module&&module.exports&&(module.exports=r),exports=r)})(this);
